### ISSUE TITLE
Short tags?

### ISSUE THREAD

**Issue by lukeocodes** [speckcommerce/speck#41] opened 2014-04-11 10:41 UTC
First stumble in the install, is the use of short tags.

They've been totally phased out of PHP5 standards. I'll modify and raise the appropriate pull request.

Thought I'd mention it!

**Comment by shipleyr** [comment] 2014-04-11 10:48
Where are short tags used? I'd not noticed any? Are you talking about in *.phtml files?

**Comment by lukeocodes** [comment] 2014-04-11 10:54
I'd suggest a full install and then do something like;

```
grep -R "<?" * | grep -v "<?php"
```

I had to enable ASP style tags and short tags!

This may have just occurred in the SpeckInstall module to be fair.

**Comment by shipleyr** [comment] 2014-04-11 10:58
SpeckInstall is not all that great - I didn't use it. I installed everything manually. Much easier. Think it was created to bridge a gap and try to make installs quicker. 

If the issue is not in this module can I propose you raise an issue/PR against the relevant modules ad close this one?

**Closed as completed** 2016-03-31 16:27 UTC
